In [1]:
import numpy as np

In [2]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [3]:
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
# row wise sum
row_sum = np.sum(data, axis=1)
row_sum

array([ 60, 150, 240])

In [7]:
# column wise sum
col_sum = np.sum(data, axis=0)
col_sum

array([120, 150, 180])

In [8]:
# minimum value
min_value = np.min(data)
min_value

np.int64(10)

In [9]:
# maximum value
max_value = np.max(data)
max_value

np.int64(90)

In [10]:
# overall mean
overall_mean = np.mean(data)
overall_mean

np.float64(50.0)