In [5]:
import numpy as np
arr1 = np.arange(1,11).astype(int)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr2 = np.arange(1,10).reshape(3,3)
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list1 = [10, 20, 30, 40, 50]
arr3 = np.array(list1)
arr3

array([10, 20, 30, 40, 50])

In [13]:
arrays = {
    "arr1": arr1,
    "arr2": arr2,
    "arr3": arr3
}
for name, arr in arrays.items():
    print(f"data type of {name} is: {(arr).dtype}")
    print(f"shape of {name} is: {(arr).shape}")


data type of arr1 is: int64
shape of arr1 is: (10,)
data type of arr2 is: int64
shape of arr2 is: (3, 3)
data type of arr3 is: int64
shape of arr3 is: (5,)
